import Achievement from '#models/achievement'
import { BaseSeeder } from '@adonisjs/lucid/seeders'

const ACHIEVEMENTS = [
  {
    slug: 'title-mvp',
    name: 'MVP',
    description: 'O mais valioso da Play.',
    icon: '🏅',
    category: 'competitive',
    criteriaType: 'match_count',
    criteriaValue: { count: 5 },
    sortOrder: 10,
  },
  {
    slug: 'title-on-fire',
    name: 'On Fire',
    description: 'Em chamas na competição.',
    icon: '🔥',
    category: 'competitive',
    criteriaType: 'win_streak',
    criteriaValue: { count: 3 },
    sortOrder: 11,
  },
  {
    slug: 'title-invicto',
    name: 'Invicto',
    description: 'Sequência imbatível.',
    icon: '📈',
    category: 'competitive',
    criteriaType: 'win_streak',
    criteriaValue: { count: 5 },
    sortOrder: 12,
  },
  {
    slug: 'title-carrasco',
    name: 'Carrasco',
    description: 'Vença sem games do adversário em nenhum set.',
    icon: '⚔️',
    category: 'competitive',
    criteriaType: 'shutout_win',
    criteriaValue: null,
    sortOrder: 13,
  },
  {
    slug: 'title-rei-da-arena',
    name: 'Rei da Arena',
    description: 'Domínio total da quadra.',
    icon: '👑',
    category: 'competitive',
    criteriaType: 'match_count',
    criteriaValue: { count: 10 },
    sortOrder: 14,
  },
  {
    slug: 'title-dono-da-quadra',
    name: 'Dono da Quadra',
    description: 'A quadra tem dono.',
    icon: '🏖️',
    category: 'competitive',
    criteriaType: 'match_count',
    criteriaValue: { count: 20 },
    sortOrder: 15,
  },
  {
    slug: 'title-predador-ranking',
    name: 'Predador de Ranking',
    description: 'Sobe posições como tubarão.',
    icon: '🦈',
    category: 'competitive',
    criteriaType: 'elo_tier',
    criteriaValue: { tier: 'ouro' },
    sortOrder: 16,
  },
  {
    slug: 'title-ice-veins',
    name: 'Ice Veins',
    description: 'Frieza sob pressão.',
    icon: '🧊',
    category: 'competitive',
    criteriaType: 'elo_tier',
    criteriaValue: { tier: 'diamante' },
    sortOrder: 17,
  },
  {
    slug: 'title-saque-torto',
    name: 'Especialista em Saque Torto',
    description: 'O saque que ninguém entende.',
    icon: '🎯',
    category: 'meme',
    criteriaType: 'match_count',
    criteriaValue: { count: 3 },
    sortOrder: 20,
  },
  {
    slug: 'title-rei-foi-fora',
    name: 'Rei do "Foi Fora"',
    description: 'Sempre tem uma bola fora.',
    icon: '👀',
    category: 'meme',
    criteriaType: 'match_count',
    criteriaValue: { count: 8 },
    sortOrder: 21,
  },
  {
    slug: 'title-craque-aquecimento',
    name: 'Craque do Aquecimento',
    description: 'Brilha antes do jogo começar.',
    icon: '🪑',
    category: 'meme',
    criteriaType: 'match_count',
    criteriaValue: { count: 15 },
    sortOrder: 22,
  },
  {
    slug: 'title-tecnico-nao-solicitado',
    name: 'Técnico Não Solicitado',
    description: 'Dá pitaco em toda jogada.',
    icon: '📢',
    category: 'meme',
    criteriaType: 'level',
    criteriaValue: { level: 5 },
    sortOrder: 23,
  },
  {
    slug: 'title-estrategia-duvidosa',
    name: 'Estratégia Duvidosa',
    description: 'Plano B? Plano aleatório.',
    icon: '🧠',
    category: 'meme',
    criteriaType: 'level',
    criteriaValue: { level: 8 },
    sortOrder: 24,
  },
  {
    slug: 'title-mvp-pos-jogo',
    name: 'MVP do Pós-Jogo',
    description: 'A festa começa depois do placar.',
    icon: '🥤',
    category: 'meme',
    criteriaType: 'match_count',
    criteriaValue: { count: 25 },
    sortOrder: 25,
  },
  {
    slug: 'title-influencer-arena',
    name: 'Influencer da Arena',
    description: 'Tudo vira conteúdo.',
    icon: '📸',
    category: 'meme',
    criteriaType: 'level',
    criteriaValue: { level: 10 },
    sortOrder: 26,
  },
  {
    slug: 'title-chinelada-master',
    name: 'Chinelada Master',
    description: 'Estilo off-court impecável.',
    icon: '🩴',
    category: 'meme',
    criteriaType: 'match_count',
    criteriaValue: { count: 30 },
    sortOrder: 27,
  },
  {
    slug: 'title-sem-tempo-bola',
    name: 'Hoje Tô Sem Tempo de Bola',
    description: 'Corre, mas não é prioridade.',
    icon: '🤷',
    category: 'meme',
    criteriaType: 'match_count',
    criteriaValue: { count: 40 },
    sortOrder: 28,
  },
  {
    slug: 'title-sniper-paralela',
    name: 'Sniper da Paralela',
    description: 'Paralela certeira.',
    icon: '🎯',
    category: 'skill',
    criteriaType: 'win_streak',
    criteriaValue: { count: 4 },
    sortOrder: 30,
  },
  {
    slug: 'title-mestre-lob',
    name: 'Mestre do Lob',
    description: 'Lob que decide.',
    icon: '🪄',
    category: 'skill',
    criteriaType: 'match_count',
    criteriaValue: { count: 12 },
    sortOrder: 31,
  },
  {
    slug: 'title-muralha-rede',
    name: 'Muralha da Rede',
    description: 'Defesa na rede.',
    icon: '🧱',
    category: 'skill',
    criteriaType: 'match_count',
    criteriaValue: { count: 18 },
    sortOrder: 32,
  },
  {
    slug: 'title-reflexo-felino',
    name: 'Reflexo Felino',
    description: 'Reflexo de gato.',
    icon: '⚡',
    category: 'skill',
    criteriaType: 'level',
    criteriaValue: { level: 12 },
    sortOrder: 33,
  },
  {
    slug: 'title-mao-veludo',
    name: 'Mão de Veludo',
    description: 'Toque suave na bola.',
    icon: '🎾',
    category: 'skill',
    criteriaType: 'match_count',
    criteriaValue: { count: 22 },
    sortOrder: 34,
  },
  {
    slug: 'title-slice-venenoso',
    name: 'Slice Venenoso',
    description: 'Slice impossível.',
    icon: '🐍',
    category: 'skill',
    criteriaType: 'elo_tier',
    criteriaValue: { tier: 'prata' },
    sortOrder: 35,
  },
  {
    slug: 'title-smash-supersonico',
    name: 'Smash Supersônico',
    description: 'Vença sem games do adversário em nenhum set.',
    icon: '🚀',
    category: 'skill',
    criteriaType: 'shutout_win',
    criteriaValue: null,
    sortOrder: 36,
  },
  {
    slug: 'title-leitor-jogada',
    name: 'Leitor de Jogada',
    description: 'Antecipa cada ponto.',
    icon: '🧠',
    category: 'skill',
    criteriaType: 'elo_tier',
    criteriaValue: { tier: 'mestre' },
    sortOrder: 37,
  },
  {
    slug: 'title-azar-da-quadra',
    name: 'Azar da Quadra',
    description: 'Duas derrotas seguidas. A Play sentiu.',
    icon: '🎲',
    category: 'troll',
    criteriaType: 'loss_streak',
    criteriaValue: { count: 2 },
    sortOrder: 40,
  },
  {
    slug: 'title-mod-aviao',
    name: 'Modo Avião',
    description: 'Três quedas seguidas. Some da rede.',
    icon: '✈️',
    category: 'troll',
    criteriaType: 'loss_streak',
    criteriaValue: { count: 3 },
    sortOrder: 41,
  },
  {
    slug: 'title-match-point-perdido',
    name: 'Rei do Match Point Perdido',
    description: 'Quatro seguidas. O ponto decisivo nunca veio.',
    icon: '😬',
    category: 'troll',
    criteriaType: 'loss_streak',
    criteriaValue: { count: 4 },
    sortOrder: 42,
  },
  {
    slug: 'title-profissional-0x6',
    name: 'Profissional do 0x6',
    description: 'Cinco derrotas seguidas. Consistência invertida.',
    icon: '🫠',
    category: 'troll',
    criteriaType: 'loss_streak',
    criteriaValue: { count: 5 },
    sortOrder: 43,
  },
  {
    slug: 'title-bola-fora',
    name: 'Especialista em Bola Fora',
    description: 'Dez partidas — nem sempre a culpa é da rede.',
    icon: '👀',
    category: 'troll',
    criteriaType: 'match_count',
    criteriaValue: { count: 10 },
    sortOrder: 44,
  },
  {
    slug: 'title-volta-amanha',
    name: 'Volto Amanhã',
    description: '25 partidas. Amanhã a gente ganha.',
    icon: '🌙',
    category: 'troll',
    criteriaType: 'match_count',
    criteriaValue: { count: 25 },
    sortOrder: 45,
  },
] as const

export default class extends BaseSeeder {
  async run() {
    for (const achievement of ACHIEVEMENTS) {
      await Achievement.updateOrCreate({ slug: achievement.slug }, achievement)
    }
  }
}
