import ShopItem from '#models/shop_item'
import { BaseSeeder } from '@adonisjs/lucid/seeders'
import db from '@adonisjs/lucid/services/db'

const TITLE_SLUGS = [
  'title-rei-da-arena',
  'title-ice-veins',
  'title-mvp',
  'title-carrasco',
  'title-invicto',
  'title-predador-ranking',
  'title-dono-da-quadra',
  'title-on-fire',
  'title-saque-torto',
  'title-rei-foi-fora',
  'title-craque-aquecimento',
  'title-tecnico-nao-solicitado',
  'title-estrategia-duvidosa',
  'title-mvp-pos-jogo',
  'title-influencer-arena',
  'title-chinelada-master',
  'title-sem-tempo-bola',
  'title-sniper-paralela',
  'title-mestre-lob',
  'title-muralha-rede',
  'title-reflexo-felino',
  'title-mao-veludo',
  'title-slice-venenoso',
  'title-smash-supersonico',
  'title-leitor-jogada',
  'title-10-bolas-rede',
  'title-perdendo-5x0',
  'title-atrasado-ganhou',
  'title-pediu-tempo-piorou',
  'title-caibra-match-point',
  'title-ganhou-vento',
  'title-tiltou-adversario',
  'title-vitoria-culposa',
  'title-sobreviveu-tiebreak',
  'title-ultimo-jogo',
] as const

const FRAME_SLUGS = [
  'frame-1',
  'frame-2',
  'frame-3',
  'frame-4',
  'frame-5',
  'frame-6',
  'frame-7',
  'frame-8',
  'frame-9',
  'frame-10',
  'frame-11',
  'frame-12',
] as const

const ALL_SLUGS = [...TITLE_SLUGS, ...FRAME_SLUGS]

export default class extends BaseSeeder {
  async run() {
    const items = [
      {
        slug: 'title-rei-da-arena',
        name: 'Rei da Arena',
        description: 'Domínio total da quadra.',
        price: 70,
        itemType: 'title',
        payload: { icon: '👑', category: 'competitive' },
        sortOrder: 10,
      },
      {
        slug: 'title-ice-veins',
        name: 'Ice Veins',
        description: 'Frieza sob pressão.',
        price: 65,
        itemType: 'title',
        payload: { icon: '🧊', category: 'competitive' },
        sortOrder: 11,
      },
      {
        slug: 'title-mvp',
        name: 'MVP',
        description: 'O mais valioso da Play.',
        price: 60,
        itemType: 'title',
        payload: { icon: '🏅', category: 'competitive' },
        sortOrder: 12,
      },
      {
        slug: 'title-carrasco',
        name: 'Carrasco',
        description: 'Elimina adversários sem piedade.',
        price: 75,
        itemType: 'title',
        payload: { icon: '⚔️', category: 'competitive' },
        sortOrder: 13,
      },
      {
        slug: 'title-invicto',
        name: 'Invicto',
        description: 'Sequência imbatível.',
        price: 80,
        itemType: 'title',
        payload: { icon: '📈', category: 'competitive' },
        sortOrder: 14,
      },
      {
        slug: 'title-predador-ranking',
        name: 'Predador de Ranking',
        description: 'Sobe posições como tubarão.',
        price: 70,
        itemType: 'title',
        payload: { icon: '🦈', category: 'competitive' },
        sortOrder: 15,
      },
      {
        slug: 'title-dono-da-quadra',
        name: 'Dono da Quadra',
        description: 'A quadra tem dono.',
        price: 55,
        itemType: 'title',
        payload: { icon: '🏖️', category: 'competitive' },
        sortOrder: 16,
      },
      {
        slug: 'title-on-fire',
        name: 'On Fire',
        description: 'Em chamas na competição.',
        price: 0,
        itemType: 'title',
        payload: { icon: '🔥', category: 'competitive' },
        sortOrder: 17,
      },

      {
        slug: 'title-saque-torto',
        name: 'Especialista em Saque Torto',
        description: 'O saque que ninguém entende.',
        price: 0,
        itemType: 'title',
        payload: { icon: '🎯', category: 'meme' },
        sortOrder: 20,
      },
      {
        slug: 'title-rei-foi-fora',
        name: 'Rei do "Foi Fora"',
        description: 'Sempre tem uma bola fora.',
        price: 30,
        itemType: 'title',
        payload: { icon: '👀', category: 'meme' },
        sortOrder: 21,
      },
      {
        slug: 'title-craque-aquecimento',
        name: 'Craque do Aquecimento',
        description: 'Brilha antes do jogo começar.',
        price: 25,
        itemType: 'title',
        payload: { icon: '🪑', category: 'meme' },
        sortOrder: 22,
      },
      {
        slug: 'title-tecnico-nao-solicitado',
        name: 'Técnico Não Solicitado',
        description: 'Dá pitaco em toda jogada.',
        price: 35,
        itemType: 'title',
        payload: { icon: '📢', category: 'meme' },
        sortOrder: 23,
      },
      {
        slug: 'title-estrategia-duvidosa',
        name: 'Estratégia Duvidosa',
        description: 'Plano B? Plano aleatório.',
        price: 30,
        itemType: 'title',
        payload: { icon: '🧠', category: 'meme' },
        sortOrder: 24,
      },
      {
        slug: 'title-mvp-pos-jogo',
        name: 'MVP do Pós-Jogo',
        description: 'A festa começa depois do placar.',
        price: 40,
        itemType: 'title',
        payload: { icon: '🥤', category: 'meme' },
        sortOrder: 25,
      },
      {
        slug: 'title-influencer-arena',
        name: 'Influencer da Arena',
        description: 'Tudo vira conteúdo.',
        price: 35,
        itemType: 'title',
        payload: { icon: '📸', category: 'meme' },
        sortOrder: 26,
      },
      {
        slug: 'title-chinelada-master',
        name: 'Chinelada Master',
        description: 'Estilo off-court impecável.',
        price: 0,
        itemType: 'title',
        payload: { icon: '🩴', category: 'meme' },
        sortOrder: 27,
      },
      {
        slug: 'title-sem-tempo-bola',
        name: 'Hoje Tô Sem Tempo de Bola',
        description: 'Corre, mas não é prioridade.',
        price: 0,
        itemType: 'title',
        payload: { icon: '🤷', category: 'meme' },
        sortOrder: 28,
      },

      {
        slug: 'title-sniper-paralela',
        name: 'Sniper da Paralela',
        description: 'Paralela certeira.',
        price: 90,
        itemType: 'title',
        payload: { icon: '🎯', category: 'skill' },
        sortOrder: 30,
      },
      {
        slug: 'title-mestre-lob',
        name: 'Mestre do Lob',
        description: 'Lob que decide.',
        price: 85,
        itemType: 'title',
        payload: { icon: '🪄', category: 'skill' },
        sortOrder: 31,
      },
      {
        slug: 'title-muralha-rede',
        name: 'Muralha da Rede',
        description: 'Defesa na rede.',
        price: 80,
        itemType: 'title',
        payload: { icon: '🧱', category: 'skill' },
        sortOrder: 32,
      },
      {
        slug: 'title-reflexo-felino',
        name: 'Reflexo Felino',
        description: 'Reflexo de gato.',
        price: 75,
        itemType: 'title',
        payload: { icon: '⚡', category: 'skill' },
        sortOrder: 33,
      },
      {
        slug: 'title-mao-veludo',
        name: 'Mão de Veludo',
        description: 'Toque suave na bola.',
        price: 70,
        itemType: 'title',
        payload: { icon: '🎾', category: 'skill' },
        sortOrder: 34,
      },
      {
        slug: 'title-slice-venenoso',
        name: 'Slice Venenoso',
        description: 'Slice impossível.',
        price: 85,
        itemType: 'title',
        payload: { icon: '🐍', category: 'skill' },
        sortOrder: 35,
      },
      {
        slug: 'title-smash-supersonico',
        name: 'Smash Supersônico',
        description: 'Smash que ecoa.',
        price: 100,
        itemType: 'title',
        payload: { icon: '🚀', category: 'skill' },
        sortOrder: 36,
      },
      {
        slug: 'title-leitor-jogada',
        name: 'Leitor de Jogada',
        description: 'Antecipa cada ponto.',
        price: 95,
        itemType: 'title',
        payload: { icon: '🧠', category: 'skill' },
        sortOrder: 37,
      },

      {
        slug: 'title-10-bolas-rede',
        name: '10 bolas na rede seguidas',
        description: 'Sequência épica na rede.',
        price: 55,
        itemType: 'title',
        payload: { icon: '💀', category: 'troll' },
        sortOrder: 40,
      },
      {
        slug: 'title-perdendo-5x0',
        name: 'Virou jogo perdendo de 5x0',
        description: 'Começou mal, terminou lenda.',
        price: 60,
        itemType: 'title',
        payload: { icon: '🫠', category: 'troll' },
        sortOrder: 41,
      },
      {
        slug: 'title-atrasado-ganhou',
        name: 'Chegou atrasado e ganhou',
        description: 'O relógio não manda.',
        price: 0,
        itemType: 'title',
        payload: { icon: '⏰', category: 'troll' },
        sortOrder: 42,
      },
      {
        slug: 'title-pediu-tempo-piorou',
        name: 'Pediu tempo e piorou',
        description: 'A pausa que não ajudou.',
        price: 50,
        itemType: 'title',
        payload: { icon: '🤕', category: 'troll' },
        sortOrder: 43,
      },
      {
        slug: 'title-caibra-match-point',
        name: 'Cãibra no match point',
        description: 'Drama no ponto decisivo.',
        price: 55,
        itemType: 'title',
        payload: { icon: '🥵', category: 'troll' },
        sortOrder: 44,
      },
      {
        slug: 'title-ganhou-vento',
        name: 'Ganhou no vento',
        description: 'A natureza ajudou.',
        price: 45,
        itemType: 'title',
        payload: { icon: '🌪️', category: 'troll' },
        sortOrder: 45,
      },
      {
        slug: 'title-tiltou-adversario',
        name: 'Tiltou o adversário',
        description: 'Psicológico dominado.',
        price: 65,
        itemType: 'title',
        payload: { icon: '🧂', category: 'troll' },
        sortOrder: 46,
      },
      {
        slug: 'title-vitoria-culposa',
        name: 'Vitória Culposa',
        description: 'Ganhou do jeito mais estranho.',
        price: 50,
        itemType: 'title',
        payload: { icon: '🎲', category: 'troll' },
        sortOrder: 47,
      },
      {
        slug: 'title-sobreviveu-tiebreak',
        name: 'Sobreviveu ao tie-break',
        description: 'Saiu vivo do super tie.',
        price: 70,
        itemType: 'title',
        payload: { icon: '🚑', category: 'troll' },
        sortOrder: 48,
      },
      {
        slug: 'title-ultimo-jogo',
        name: 'Último jogo (jogou mais 4)',
        description: 'Prometeu parar e não parou.',
        price: 0,
        itemType: 'title',
        payload: { icon: '🧎', category: 'troll' },
        sortOrder: 49,
      },

      {
        slug: 'frame-1',
        name: 'Coroa de Ouro',
        description: 'Moldura de campeão com louros e coroa.',
        price: 80,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/1.png', inset: 18 },
        sortOrder: 70,
      },
      {
        slug: 'frame-2',
        name: 'Chama da Sequência',
        description: 'Moldura de fogo para quem está em streak.',
        price: 75,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/2.png', inset: 18 },
        sortOrder: 80,
      },
      {
        slug: 'frame-3',
        name: 'Verde Palpiteiro',
        description: 'Moldura oficial do app.',
        price: 0,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/3.png', inset: 18 },
        sortOrder: 90,
      },
      {
        slug: 'frame-4',
        name: 'Neon da Quadra',
        description: 'Brilho neon estilo arcade.',
        price: 60,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/4.png', inset: 18 },
        sortOrder: 100,
      },
      {
        slug: 'frame-5',
        name: 'Pódio de Troféus',
        description: 'Moldura de medalhas e troféus.',
        price: 70,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/5.png', inset: 18 },
        sortOrder: 110,
      },
      {
        slug: 'frame-6',
        name: 'Pôr do Sol na Areia',
        description: 'Tons quentes de praia e pôr do sol.',
        price: 45,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/6.png', inset: 18 },
        sortOrder: 120,
      },
      {
        slug: 'frame-7',
        name: 'VIP Diamante',
        description: 'Moldura premium cristalina.',
        price: 100,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/7.png', inset: 18 },
        sortOrder: 130,
      },
      {
        slug: 'frame-8',
        name: 'Raio Certeiro',
        description: 'Energia elétrica de palpite certo.',
        price: 55,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/8.png', inset: 18 },
        sortOrder: 140,
      },
      {
        slug: 'frame-9',
        name: 'Festa da Play',
        description: 'Confete e celebração do grupo.',
        price: 40,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/9.png', inset: 18 },
        sortOrder: 150,
      },
      {
        slug: 'frame-10',
        name: 'Lenda Negra',
        description: 'Moldura sombria de lenda dos palpites.',
        price: 90,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/10.png', inset: 18 },
        sortOrder: 160,
      },
      {
        slug: 'frame-11',
        name: 'Onda do Beach',
        description: 'Ondas e espuma do litoral.',
        price: 45,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/11.png', inset: 18 },
        sortOrder: 170,
      },
      {
        slug: 'frame-12',
        name: 'Bronze Iniciante',
        description: 'Moldura de bronze para começar a coleção.',
        price: 0,
        itemType: 'avatar_frame',
        payload: { frameSrc: '/shop/frames/12.png', inset: 18 },
        sortOrder: 180,
      },
    ]

    for (const item of items) {
      await ShopItem.updateOrCreate({ slug: item.slug }, item)
    }

    const obsolete = await db
      .from('shop_items')
      .whereNotIn('slug', [...ALL_SLUGS])
      .select('id')

    const obsoleteIds = obsolete.map((row) => row.id)
    if (obsoleteIds.length > 0) {
      await db.from('user_equipped_items').whereIn('shop_item_id', obsoleteIds).delete()
      await db.from('user_purchases').whereIn('shop_item_id', obsoleteIds).delete()
      await db.from('shop_items').whereIn('id', obsoleteIds).delete()
    }
  }
}
