/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Avatars: () => import('#controllers/avatars_controller'),
  Groups: () => import('#controllers/groups_controller'),
  History: () => import('#controllers/history_controller'),
  Matches: () => import('#controllers/matches_controller'),
  Members: () => import('#controllers/members_controller'),
  NewAccount: () => import('#controllers/new_account_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Session: () => import('#controllers/session_controller'),
  Shop: () => import('#controllers/shop_controller'),
}
