/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AchievementSchema extends BaseModel {
  static $columns = ['category', 'createdAt', 'criteriaType', 'criteriaValue', 'description', 'icon', 'id', 'name', 'slug', 'sortOrder'] as const
  $columns = AchievementSchema.$columns
  @column()
  declare category: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare criteriaType: string
  @column()
  declare criteriaValue: any | null
  @column()
  declare description: string | null
  @column()
  declare icon: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
}

export class ArenaSchema extends BaseModel {
  static $columns = ['city', 'createdAt', 'id', 'name', 'updatedAt'] as const
  $columns = ArenaSchema.$columns
  @column()
  declare city: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AvatarFrameSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'payload', 'slug', 'sortOrder', 'unlockLevel'] as const
  $columns = AvatarFrameSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare payload: any
  @column()
  declare slug: string
  @column()
  declare sortOrder: number
  @column()
  declare unlockLevel: number
}

export class GroupMemberSchema extends BaseModel {
  static $columns = ['createdAt', 'groupId', 'id', 'role', 'userId'] as const
  $columns = GroupMemberSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare groupId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare role: string
  @column()
  declare userId: number
}

export class GroupSchema extends BaseModel {
  static $columns = ['createdAt', 'id', 'inviteCode', 'name', 'updatedAt'] as const
  $columns = GroupSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare inviteCode: string
  @column()
  declare name: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class GuestPlayerInviteSchema extends BaseModel {
  static $columns = ['claimedAt', 'claimedUserId', 'createdAt', 'createdByUserId', 'displayName', 'groupId', 'id', 'token', 'updatedAt'] as const
  $columns = GuestPlayerInviteSchema.$columns
  @column.dateTime()
  declare claimedAt: DateTime | null
  @column()
  declare claimedUserId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number
  @column()
  declare displayName: string
  @column()
  declare groupId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class MatchPlayerSchema extends BaseModel {
  static $columns = ['displayName', 'guestInviteId', 'id', 'matchId', 'side', 'userId'] as const
  $columns = MatchPlayerSchema.$columns
  @column()
  declare displayName: string | null
  @column()
  declare guestInviteId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare matchId: number
  @column()
  declare side: number
  @column()
  declare userId: number | null
}

export class MatchRewardSchema extends BaseModel {
  static $columns = ['createdAt', 'eloAfter', 'eloDelta', 'id', 'matchId', 'userId', 'xpAwarded'] as const
  $columns = MatchRewardSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eloAfter: number
  @column()
  declare eloDelta: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare matchId: number
  @column()
  declare userId: number
  @column()
  declare xpAwarded: number
}

export class MatchSchema extends BaseModel {
  static $columns = ['arenaId', 'createdAt', 'createdByUserId', 'groupId', 'id', 'score', 'status', 'statusChangedAt', 'updatedAt', 'winnerSide'] as const
  $columns = MatchSchema.$columns
  @column()
  declare arenaId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare createdByUserId: number
  @column()
  declare groupId: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare score: any | null
  @column()
  declare status: string
  @column.dateTime()
  declare statusChangedAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare winnerSide: number | null
}

export class UserAchievementSchema extends BaseModel {
  static $columns = ['achievementId', 'id', 'unlockedAt', 'userId'] as const
  $columns = UserAchievementSchema.$columns
  @column()
  declare achievementId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare unlockedAt: DateTime
  @column()
  declare userId: number
}

export class UserEquippedItemSchema extends BaseModel {
  static $columns = ['achievementId', 'avatarFrameId', 'id', 'itemType', 'slot', 'userId'] as const
  $columns = UserEquippedItemSchema.$columns
  @column()
  declare achievementId: number | null
  @column()
  declare avatarFrameId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare itemType: string
  @column()
  declare slot: boolean
  @column()
  declare userId: number
}

export class UserUnlockedFrameSchema extends BaseModel {
  static $columns = ['avatarFrameId', 'id', 'unlockedAt', 'userId'] as const
  $columns = UserUnlockedFrameSchema.$columns
  @column()
  declare avatarFrameId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare unlockedAt: DateTime
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarPath', 'courtSide', 'createdAt', 'dominantHand', 'elo', 'email', 'fullName', 'funLabel', 'googleId', 'id', 'level', 'nickname', 'password', 'skillLevel', 'updatedAt', 'xp'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarPath: string | null
  @column()
  declare courtSide: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare dominantHand: string | null
  @column()
  declare elo: number
  @column()
  declare email: string
  @column()
  declare fullName: string | null
  @column()
  declare funLabel: string | null
  @column()
  declare googleId: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare level: number
  @column()
  declare nickname: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare skillLevel: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare xp: number
}
